<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Middleware\MonologMiddleware::class => App\Middleware\MonologMiddlewareFactory::class,
            User\Handler\GetAllUserHandler::class => User\Handler\GetAllUserHandlerFactory::class,
            User\Handler\GetUserByIdHandler::class => User\Handler\GetUserByIdHandlerFactory::class,
            User\Handler\InsertUserHandler::class => User\Handler\InsertUserHandlerFactory::class,
        ],
    ],
];
